# Generated by Django 5.2.4 on 2025-07-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={'verbose_name': 'Convénio', 'verbose_name_plural': 'Convénios'},
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='exame',
            options={'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pedidoexame',
            options={'verbose_name': 'Pedido de Exame', 'verbose_name_plural': 'Pedidos de Exames'},
        ),
        migrations.AlterModelOptions(
            name='prescricao',
            options={'verbose_name': 'Prescrição', 'verbose_name_plural': 'Prescrições'},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name': 'Prontuário', 'verbose_name_plural': 'Prontuários'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='core.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='codigo_ans',
            field=models.CharField(help_text='Registo na Agência Nacional de Saúde', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.convenio'),
        ),
        migrations.AlterField(
            model_name='pedidoexame',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_exames', to='core.consulta'),
        ),
        migrations.AlterField(
            model_name='pedidoexame',
            name='exame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exame'),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescricoes', to='core.consulta'),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medicamento'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.paciente'),
        ),
    ]
